# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sledge-Plugin-DebugMessage
version:      0.02
version_from: lib/Sledge/Plugin/DebugMessage.pm
installdirs:  site
requires:
    Bundle::Sledge:                0
    Data::Dumper:                  2.121
    Jcode:                         0.88
    Template:                      2.14
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
