---
abstract: 'show the debug message'
author:
  - unknown
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sledge-Plugin-DebugMessage
no_index:
  directory:
    - t
    - inc
provides:
  Sledge::Plugin::DebugMessage:
    file: lib/Sledge/Plugin/DebugMessage.pm
    version: 0.03
requires:
  Bundle::Sledge: 0
  Data::Dumper: 2.121
  Jcode: 0.88
  Template: 2.14
  Test::More: 0.32
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
